title: Omniverse From Scratch
email: omniversefromscratch@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  omniversefromscratch

# Build settings
# theme: minima
#remote_theme: b2a3e8/jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jemoji
  - jekyll-seo-tag

header_pages:
  - index.md
  # - templates.md
  # - projects.md
  # - deployments.md
  # - cycles.md
  # - bounties.md
  # - community.md
  # - learn.md
  # - support.md
  # - extensions.md
  # - teams.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: 'Learn more on <a target="_blank" href="https://www.youtube.com/@omniversefromscratch">YouTube</a> | <a target="_blank" href="https://www.patreon.com/omniversefromscratch">Help us make more videos</a>'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
